### ISSUE TITLE
可否将HTML部分开源？

### ISSUE THREAD

**Issue by 5percent** [LangrisserApp/LangrisserApp.github.io#1]
可以帮忙优化体验，写写JS、CSS什么的问题不大

**Comment by LangrisserApp** [comment]
速度的主要问题是 服务器 性能和带宽，不是代码
代码部分并不是纯 html，并且目前还乱的很

**Comment by 5percent** [comment]
可以考虑把数据接口拆出来，改成异步请求，在页面里用localstorage做缓存。只返回纯静态html的话，单台机器抗压几十万pv问题不大。

或者更粗暴一点就是把数据存成json扔cdn上，减轻服务器压力，用脚本定期更新。

**Comment by LangrisserApp** [comment]
不想拆成数据接口，也不想放成 json，容易被人调用和引用，服务器压力就更大了，速度会更慢  :(
我已经加了 cloudflare 了，目前访问速度已经大幅改观
